### ISSUE TITLE
Add Swagger Open API endpoint  Edit

### ISSUE THREAD

**Issue by joeworkman** [totalcms/cms#1]

**Comment by odan** [comment]
Done. See /docs

![image](https://user-images.githubusercontent.com/781074/159355094-1fb8f413-df9e-4bcc-86dc-cbeebf2aab5b.png)

**Comment by odan** [comment]
We should migrate the Swagger schema to OpenAPI v3.0.0 and use Yaml as default file format.

**Comment by joeworkman** [comment]
I do not see `/docs`. I tried running `composer build` but that did not work. 

I updated everything to be Open API 3 and the file format is YAML. There is also a JSON file. This makes it a bit easier for me to edit since I can use an app for editing the contents. 

All of the basics are there. I need to do more work on the request body and response definitions.

**Comment by odan** [comment]
I mean the URL path, for example: http://localhost/docs

I have not added `composer build`. What is `artifact` for a tool?

**Comment by joeworkman** [comment]
I have no clue to be honest. I though you added it.

**Comment by odan** [comment]
I think we can close this because the docs are done.
